### ISSUE TITLE
Audio artefacts

### ISSUE THREAD

**Issue by Uriopass** [bjorn3/rustc_codegen_cranelift#1142]
This is the official issue for the audio artefacts I had in #1129
I tried to reproduce the problem, however I hit an incredibly weird bug.

When compiling this snippet alone
```rust
use rodio::Source;

fn main() {
    let (a, b) = rodio::OutputStream::try_default().unwrap();
    let buf = std::fs::read("music1.ogg").ok().unwrap();

    let s = rodio::Decoder::new(std::io::Cursor::new(buf)).unwrap();
    b.play_raw(s.convert_samples()).unwrap();
    loop {}
}
```

everything works fine and the music sounds good.

However when I compile the _exact same main_ with the _exact same audio file_ in my big project with lots of dependencies, there are hugs artefacts which look like this in audacity: Top is what is output and bottom is expected.
![image](https://user-images.githubusercontent.com/5420739/108494666-1d810900-72a8-11eb-8e4f-3f758cdf5d25.png)

I tried deleting the target folder and rebuilding and I still got the artefacts.

Then I found that by removing theses directives about optimizing in my workspace Cargo.toml
```toml
[profile.dev.build-override]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2

[profile.dev.package.common]
opt-level = 2

[profile.dev.package.egregoria]
opt-level = 0

[profile.dev.package.map_model]
opt-level = 0

[profile.dev.package.native_app] # <- main binary
opt-level = 0

[profile.dev.package.imgui-inspect]
opt-level = 1

[profile.dev.package.imgui-inspect-derive]
opt-level = 1
```

the audio artefacts were gone !

However, when reenabling 
```toml
[profile.dev.package."*"]
opt-level = 2
```
the artefacts came back.

So I started removing dependencies, and I found that, basically, enabling optimizations on rodio using cg_clif gave thoses artefacts..

You can find a repo to reproduce here.
https://github.com/Uriopass/cranelift_bug

EDIT: 
Now that I think about it, you still have to dive a bit further, it's not like there's no dependencies. I'll try on cpal examples.

**Comment by bjorn3** [comment]
> So I started removing dependencies, and I found that, basically, enabling optimizations on rodio using cg_clif gave thoses artefacts.

Thanks for the investigation! This must be a miscompilation caused by one of the optimizations then. I will see if I can narrow down which optimization is responsible.

**Comment by bjorn3** [comment]
By the way, which license is the repro?

**Comment by Uriopass** [comment]
Interestingly, when I use a simple sin wave as a source, I get normal sounding results! I wonder if it comes from the vorbis decoder, I'll try the mp3 decoder.

**Comment by Uriopass** [comment]
Added the Unlicense LICENCE :-)

**Comment by bjorn3** [comment]
Thanks. I won't have to worry about adding a test derived from it to cg_clif then.

**Comment by Uriopass** [comment]
I confirm that using the mp3 decoder gives normal result. It probably comes from the vorbis decoder used by rodio: lewton.
https://github.com/RustAudio/lewton

**Comment by Uriopass** [comment]
Adding 
```toml
[profile.dev.package.lewton]
opt-level = 0
```

does solve the artefacts issues
and
```toml
[profile.dev.package.lewton]
opt-level = 1
```
still gives artefacts.

Also, generating a sin wave ogg file gives normal result (maybe it compresses well ?)
